name: Copyright Check

on:
  pull_request:
    branches: [main, develop]
    paths:
      - "**.py"
      - "**.js"
      - "**.ts"
      - "**.jsx"
      - "**.tsx"

jobs:
  check-copyright:
    runs-on: ubuntu-latest
    name: Verify Copyright Headers

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v41
        with:
          files: |
            **/*.py
            **/*.js
            **/*.ts
            **/*.jsx
            **/*.tsx

      - name: Check copyright headers
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          echo "Checking copyright headers in changed files..."

          MISSING_COPYRIGHT=()
          CURRENT_YEAR=$(date +%Y)

          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "Checking: $file"

            # Skip test files and __init__.py
            if [[ "$file" == *"test_"* ]] || [[ "$file" == *"__init__.py" ]]; then
              echo "  ⏭️  Skipping (test file or __init__.py)"
              continue
            fi

            # Check for copyright header
            if ! grep -q "Copyright (c)" "$file"; then
              MISSING_COPYRIGHT+=("$file")
              echo "  ❌ Missing copyright header"
            else
              # Verify year is current
              if ! grep -q "Copyright (c) .*$CURRENT_YEAR" "$file"; then
                echo "  ⚠️  Warning: Copyright year may be outdated"
              else
                echo "  ✅ Copyright header present"
              fi
            fi
          done

          if [ ${#MISSING_COPYRIGHT[@]} -ne 0 ]; then
            echo ""
            echo "❌ The following files are missing copyright headers:"
            printf '%s\n' "${MISSING_COPYRIGHT[@]}"
            echo ""
            echo "Please add the following header to each file:"
            echo ""
            echo "# Copyright (c) $CURRENT_YEAR Python RAG Project Team"
            echo "# SPDX-License-Identifier: MIT"
            echo "# Author: Vinícius Uchita <viniciusuchita@gmail.com>"
            echo ""
            exit 1
          fi

          echo ""
          echo "✅ All files have proper copyright headers!"

      - name: Comment PR
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '❌ **Copyright Check Failed**\n\nSome files are missing copyright headers. Please add them before merging.\n\nSee the workflow logs for details.'
            })
